name: Pruebas con Emulador de Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Ejecutar pruebas instrumentadas
    runs-on: ubuntu-latest # Cambiado a Linux (KVM compatible)

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Habilitar la aceleración de hardware reactiva (KVM)
        run: |
          echo "Habilitando KVM..."
          sudo chown $USER /dev/kvm

      - name: Instalar Android SDK y generar Emulador
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 31          # API 31 es la más rápida y estable en servidores Linux de GitHub
          target: default
          arch: x86_64           # Al usar Linux volvemos a x86_64, que es nativo para estas máquinas
          profile: Nexus 6
          script: ./gradlew connectedCheck


