name: Maestro Cloud Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  maestro-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Verify installation
        run: maestro --version

      - name: Run Maestro Cloud tests
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
          MAESTRO_PROJECT_ID: ${{ secrets.MAESTRO_PROJECT_ID }}
        run: |
          maestro cloud --device-os "android-34" --api-key $MAESTRO_API_KEY --project-id $MAESTRO_PROJECT_ID --app-file android/app/build/outputs/apk/release/app-release.apk --flows .maestro/flows