name: RN Build + Maestro Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    outputs:
      apk-path: ${{ steps.set-apk.outputs.apk-path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Set APK path
        id: set-apk
        run: |
          echo "apk-path=android/app/build/outputs/apk/release/app-release.apk" >> $GITHUB_OUTPUT

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk


  maestro-tests:
    name: Maestro Cloud Tests
    runs-on: ubuntu-latest
    needs: build-android   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: app

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run Maestro Cloud tests
        env:
          MAESTRO_CLOUD_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
          MAESTRO_PROJECT_ID: ${{ secrets.MAESTRO_PROJECT_ID }}
        run: maestro cloud --device-os "android-34" --api-key $MAESTRO_CLOUD_API_KEY --project-id $MAESTRO_PROJECT_ID app/app-release.apk --flows .maestro/flows